namespace :import do
  desc "Import all 457 variables from BP_QTY_CALCS.T3D"
  task bp_variables: :environment do
    variables = [
      "# of Units",
      "#1020ExternalDoors",
      "#1525Bath",
      "#1675Bath",
      "#1750Bath",
      "#225WPsSale",
      "#2WPsSale",
      "#2waySwitch",
      "#300WPsSale",
      "#3in1",
      "#450GrabRails",
      "#4WPsSale",
      "#600GrabRails",
      "#60CanopyRange",
      "#60ElecCooktop",
      "#60FreestandingOven",
      "#60GasCooktop",
      "#60Oven",
      "#60SlideRange",
      "#60UndermountRange",
      "#720 doors",
      "#820 doors",
      "#820ExternalDoors",
      "#900GrabRails",
      "#90CanopyRange",
      "#90ElecCooktop",
      "#90FreestandingOven",
      "#90GasCooktop",
      "#90Oven",
      "#90SlideRange",
      "#90UndermountRange",
      "#920ExternalDoors",
      "#AC25",
      "#AC35",
      "#AC5",
      "#AC6",
      "#AC71",
      "#ACSPLITS",
      "#AdjustableBench",
      "#Basin_Mixer",
      "#Bath",
      "#BlackPlastic",
      "#BlindAutomation",
      "#Ceiling Fan",
      "#Cooktops",
      "#Cornerbar Sales",
      "#DGPOUSB",
      "#DataPoints",
      "#Dbar Sales",
      "#DisabledBasins",
      "#DisabledShower",
      "#DisabledToilets",
      "#Dishwashers",
      "#DoorOpenerEXT",
      "#DoorOpenerINT",
      "#Double GPO",
      "#Double WGPO",
      "#DoubleSpotlights",
      "#DoubleSpotlights+Sensor",
      "#DoubleTowelRail",
      "#Downlights",
      "#Downpipes",
      "#Drains",
      "#Drawers",
      "#Exhaust Fans",
      "#ExtCeilingFan",
      "#ExtWallLights",
      "#ExternalDoors",
      "#ExternalDoorsWet",
      "#ExternalSlabs",
      "#Fridges",
      "#Garages",
      "#GasPoints",
      "#InsetBaths",
      "#IntWallLights",
      "#KitchenSink",
      "#LH1020Doors",
      "#LH112JAMBS",
      "#LH2340112JAMBS",
      "#LH241020Doors",
      "#LH24620Doors",
      "#LH24720Doors",
      "#LH24820Doors",
      "#LH24870Doors",
      "#LH24920Doors",
      "#LH620Doors",
      "#LH720Doors",
      "#LH820Doors",
      "#LH820GarageDoors",
      "#LH870Doors",
      "#LH920Doors",
      "#LHCareKitchenSink",
      "#LHDoors",
      "#LHGrabRail",
      "#LHKitchenSink",
      "#LHLO1020Doors",
      "#LHLO112JAMBS",
      "#LHLO241020Doors",
      "#LHLO24720Doors",
      "#LHLO24820Doors",
      "#LHLO24870Doors",
      "#LHLO24920Doors",
      "#LHLO720Doors",
      "#LHLO820Doors",
      "#LHLO870Doors",
      "#LHLO920Doors",
      "#LdyTubs",
      "#MeshSquaresSales",
      "#Microwaves",
      "#NDISDoubleGPO",
      "#NDISDoubleGPOUSB",
      "#NDISSingleGPO",
      "#NdisRollInRobes",
      "#OOARobe",
      "#PassageHandles",
      "#Pendants",
      "#Penetrations",
      "#PhonePoints",
      "#Piers",
      "#Posts",
      "#PrivacyHandles",
      "#RH1020Doors",
      "#RH112JAMBS",
      "#RH2340112JAMBS",
      "#RH241020Doors",
      "#RH24620Doors",
      "#RH24720Doors",
      "#RH24820Doors",
      "#RH24870Doors",
      "#RH24920Doors",
      "#RH620Doors",
      "#RH720Doors",
      "#RH820Doors",
      "#RH820GarageDoors",
      "#RH870Doors",
      "#RH920Doors",
      "#RHCareKitchenSink",
      "#RHDoors",
      "#RHGrabRail",
      "#RHKitchenSink",
      "#RHLO1020Doors",
      "#RHLO112JAMBS",
      "#RHLO241020Doors",
      "#RHLO24720Doors",
      "#RHLO24820Doors",
      "#RHLO24870Doors",
      "#RHLO24920Doors",
      "#RHLO720Doors",
      "#RHLO820Doors",
      "#RHLO870Doors",
      "#RHLO920Doors",
      "#Rangehoods",
      "#RecessedVanityBasins",
      "#RobePosts",
      "#Robes",
      "#Sensors",
      "#ShowerRails",
      "#Showers",
      "#Single GPO",
      "#Single GPO Roof",
      "#Single WGPO",
      "#SingleSpotlights",
      "#SingleSpotlights+Sensor",
      "#SinkMixer",
      "#SlabGroundSpacersSales",
      "#SmokeDetectors",
      "#SolarPanels",
      "#StandAloneTubs",
      "#TVPoints",
      "#TapeSlab",
      "#ToiletRollHolders",
      "#Toilets",
      "#TrenchMesh3-TM",
      "#TrenchMeshSupportSales",
      "#UndermountSink",
      "#VanityBasins",
      "#WallMountedBasin",
      "#WallOvenCab",
      "#Wall_Mixer",
      "#Watertank",
      "#Watertank10000L",
      "#Watertank2000L",
      "#Watertank3000L",
      "#Watertank4000L",
      "#Watertank5000L",
      "#WindowActuator",
      "#WindowsLintels",
      "#WirShelves",
      "#WireTie",
      "#Zbar Sales",
      "#doubledoors",
      "#integratedFridge",
      "#ofGables",
      "#ofGlassSliders",
      "#ofRidges",
      "#ofStarterBars",
      "#ofWindows",
      "#ovens",
      "20mmBenchtopM2",
      "20mmWaterfallEnds",
      "40mmBenchtopM2",
      "40mmWaterfallEnds",
      "70mmStuds",
      "Access Token",
      "AccessTokenX",
      "AdhTotalDraw",
      "Alfresco Area",
      "AllWallTilesM2",
      "AppliancePrice",
      "AwGlassM2",
      "AxonLm",
      "BalRating",
      "BalconyArea",
      "BathFloorTilesM2",
      "BathWallTilesM2",
      "BenchPrice",
      "Blinds",
      "BlindsQTY",
      "BlockLength",
      "BlockWidth",
      "BreakfastBarLamLm",
      "BreakfastBarLm",
      "BricksLm",
      "BuildBoundary",
      "CONSTRUCTION ID",
      "CabinetryPrice",
      "CarpenterPrices",
      "CarpetM2",
      "CaulkingLm",
      "CavitySlider1020",
      "CavitySlider720",
      "CavitySlider820",
      "CavitySlider870",
      "CavitySlider920",
      "CementExternalCorners",
      "CementInternalCorners",
      "CementSheetGableM2",
      "CementSheetLm",
      "CivicPrice",
      "CladdingLm",
      "Class3",
      "Closest Mass",
      "CoLiving",
      "Code",
      "ColouredConcreteM2",
      "ColouredConcreteM3",
      "CommisionPrice",
      "Component Tags",
      "ConcreteM2",
      "ContractAmount",
      "ContractPrice",
      "Cooktop Width",
      "Count",
      "CovercreteM2",
      "CupboardShelvingLM",
      "CurrentColourSelectionID",
      "CurrentColourSelectionTitle",
      "DelayBetweenProcessPO",
      "DemolitionPrice",
      "DeskTopsm2",
      "DhGlassM2",
      "DoorBool",
      "DoorBool2",
      "DrawersLM",
      "DuctedAC",
      "EB_BathroomCount",
      "EB_BedroomCount",
      "EB_Entry_Count",
      "EB_Interior_Room_Count",
      "EB_KitchenCount",
      "EB_LaundryCount",
      "EB_RoomId",
      "EB_RoomTitle",
      "EB_ToiletCount",
      "EasyBuildSelected",
      "EasyBuildSelectedWithModel",
      "EasyTexLm",
      "EasylapLm",
      "ElectricianPrice",
      "EnsFloorTilesM2",
      "EnsWallTilesM2",
      "ExposedAggregateM2",
      "ExposedAggregateM3",
      "ExternalStripDrain",
      "ExternalTilesM2",
      "FFBrickSillLm",
      "FFCeilingHeight",
      "FFCementSheetM2",
      "FFLivingArea",
      "FFWeatherboardM2",
      "FFWetArea",
      "FJPR3111",
      "FJPR3131",
      "FJPR4242",
      "FJPR6642",
      "FaceFirstBrickM2",
      "FaceGroundBrickM2",
      "Fascia Length",
      "Fascia/Gutter Length",
      "FeatureFirstBrickM2",
      "FeatureGroundBrickM2",
      "Flood",
      "FlyScreens",
      "FullSlabOrder",
      "GAS",
      "GFBrickSillLm",
      "GFCeilingHeight",
      "GFCementSheetM2",
      "GFLivingArea",
      "GFWeatherboardM2",
      "Garage",
      "Garage Area",
      "GarageLm",
      "GarageQTY",
      "GasFitPrice",
      "GasSource",
      "GlassM2",
      "GreyWater",
      "Gutter Length",
      "HWSElectric",
      "HWSGasBottles",
      "HWSGasLine",
      "HWSSolar",
      "HardieTexBaseSheetLm",
      "HardiplankM2",
      "Height",
      "HipsLm",
      "HybridM2",
      "InKitchen",
      "InternalM2",
      "InternalStripDrain",
      "JOBNUMBER",
      "Job Number",
      "Job_JSON",
      "KitDelivery",
      "KitchenWallTilesM2",
      "KitchenbenchLamLm",
      "KitchenbenchLm",
      "LdyWallTilesM2",
      "Length",
      "LineaM2",
      "LinenLm",
      "Mass'",
      "MirrorARRAY",
      "MirrorsQTY",
      "Misc1Price",
      "Misc2Price",
      "Misc3Price",
      "NDISTEKNA",
      "NDISYesNo",
      "New Tab ID",
      "NewVar",
      "NoiseCategory",
      "OverheadCupboards",
      "PACKAGE",
      "PB_ID_LENGTH",
      "PLYM2",
      "PLYSheets",
      "PMAD1020",
      "PMAD820",
      "PMAD920",
      "POID",
      "PO_Painter",
      "PSA4211",
      "PSA4219",
      "PSA6611",
      "PainterPrices",
      "PantryCabinetLm",
      "PartiWallBelowRoofm2",
      "PartitionM2",
      "Pier Height",
      "Pier Lm",
      "PlainConcreteM2",
      "PlainConcreteM3",
      "Plasterboard m2",
      "PlastererPrice",
      "PlumbPrice",
      "PlumbingGearPrice",
      "Porch Area",
      "Post FormedDeskLm",
      "Post FormedDeskm2",
      "PowerLine",
      "ProcessingItemsOnDB",
      "ProductPackage",
      "ProvisionalSum",
      "PwdrWallTilesM2",
      "QTYS_only",
      "QuickSpec_BAL",
      "QuickSpec_SOIL",
      "R1-5BattsM2",
      "R2-5BattsM2",
      "R3-0BattsM2",
      "R3-5BattsM2",
      "R4-1BattsM2",
      "R5-0BattsM2",
      "RefCabinetLm",
      "RenderedM2",
      "RidgeLm",
      "RobeLm",
      "Roller Blinds",
      "Roof Area",
      "RoomId",
      "SOF2406",
      "SalesYesNo",
      "SelectionsContentForId",
      "SelectionsOnDB",
      "Shape",
      "ShowerARRAY",
      "Showers",
      "ShowersQTY",
      "SiteArea",
      "SmallGasBottles",
      "SmallLotCode",
      "SoilClass",
      "StructFlyScreen",
      "SwGlassM2",
      "TORSIONYesNo",
      "TabIdList",
      "TeknaKitchen",
      "TeknaRenoBut",
      "Temp",
      "TilerPrices",
      "TilesM2",
      "TilesPrice",
      "TotalBrickM2",
      "TotalFFBrickM2",
      "TotalFeatureBrickM2",
      "TotalGFBrickM2",
      "TotalM2",
      "TravelAllowance",
      "Type",
      "UndersideCupboards",
      "UseableModelsInJob_Temp",
      "ValleyLm",
      "VanityLm",
      "Vinyl Array",
      "VinylArrayQty",
      "VinylM2",
      "WCWallTilesM2",
      "WRCQTY",
      "WRQTY",
      "WardrobeDoors",
      "WardrobeDoorsQTY",
      "WatertankList",
      "WatertankType",
      "WeatherboardGableM2",
      "WetAreaM2",
      "WetSeal Array",
      "WetSealLM",
      "WetSealQTY",
      "WetSealShape",
      "Width",
      "WindPrice",
      "WindRating",
      "Windows",
      "WindowsQty",
      "m3ConcreteSales"
    ]

    puts "Found #{variables.length} variables to import"

    created_count = 0
    skipped_count = 0

    variables.each do |var_name|
      if UnrealVariable.exists?(variable_name: var_name)
        skipped_count += 1
        puts "Skipped: #{var_name} (already exists)"
      else
        UnrealVariable.create!(
          variable_name: var_name,
          claude_value: 0,
          rules: nil
        )
        created_count += 1
        puts "Added: #{var_name}"
      end
    end

    puts "\n=== SUMMARY ==="
    puts "Added: #{created_count} new variables"
    puts "Skipped: #{skipped_count} (already exist)"
    puts "Total in DB: #{UnrealVariable.count}"
  end
end
